old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbit_mq'
            port:     5672
            user:     '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASS)%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: true

            # requires php-amqplib v2.4.1+
            heartbeat: 10

            #requires php_sockets.dll
            use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            url: 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASS)%@localhost:5672/vhost?lazy=1&connection_timeout=6'
    producers:
        test_producer:
            class:            App\Service\CustomProducer
            connection:       default
            exchange_options: {name: 'test-queue', type: direct}
    consumers:
        test_consumer1:
            connection:       default
            exchange_options: {name: 'test-queue', type: direct}
            queue_options:    {name: 'test-queue'}
            callback:         App\Service\TestConsumeService
        test_consumer2:
            connection:       default
            exchange_options: {name: 'test-queue', type: direct}
            queue_options:    {name: 'test-queue'}
            callback:         App\Service\TestConsumeService
        test_consumer3:
            connection:       default
            exchange_options: {name: 'test-queue', type: direct}
            queue_options:    {name: 'test-queue'}
            callback:         App\Service\TestConsumeService
        test_consumer4:
            connection:       default
            exchange_options: {name: 'test-queue', type: direct}
            queue_options:    {name: 'test-queue'}
            callback:         App\Service\TestConsumeService
