version: '3'

services:
  database:
    build:
      context: ./docker/database
    depends_on:
      - rabbit_mq
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./var/data:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    depends_on:
      - database
      - rabbit_mq
    volumes:
      - .:/srv/api
    links:
      - database:db

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/srv/api
    links:
      - php

  rabbit_mq:
    build:
      context: ./docker/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./var/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./var/log/rabbitmq/:/var/log/rabbitmq
